/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EventsRouteImport } from './routes/events'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EventsEventIdIndexRouteImport } from './routes/events_.$eventId.index'
import { Route as EventsEventIdArtistRouteImport } from './routes/events_.$eventId.artist'
import { Route as EventsEventIdAdminRouteImport } from './routes/events_.$eventId.admin'

const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdIndexRoute = EventsEventIdIndexRouteImport.update({
  id: '/events_/$eventId/',
  path: '/events/$eventId/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdArtistRoute = EventsEventIdArtistRouteImport.update({
  id: '/events_/$eventId/artist',
  path: '/events/$eventId/artist',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsEventIdAdminRoute = EventsEventIdAdminRouteImport.update({
  id: '/events_/$eventId/admin',
  path: '/events/$eventId/admin',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/events': typeof EventsRoute
  '/events/$eventId/admin': typeof EventsEventIdAdminRoute
  '/events/$eventId/artist': typeof EventsEventIdArtistRoute
  '/events/$eventId': typeof EventsEventIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/events': typeof EventsRoute
  '/events/$eventId/admin': typeof EventsEventIdAdminRoute
  '/events/$eventId/artist': typeof EventsEventIdArtistRoute
  '/events/$eventId': typeof EventsEventIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/events': typeof EventsRoute
  '/events_/$eventId/admin': typeof EventsEventIdAdminRoute
  '/events_/$eventId/artist': typeof EventsEventIdArtistRoute
  '/events_/$eventId/': typeof EventsEventIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/events'
    | '/events/$eventId/admin'
    | '/events/$eventId/artist'
    | '/events/$eventId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/events'
    | '/events/$eventId/admin'
    | '/events/$eventId/artist'
    | '/events/$eventId'
  id:
    | '__root__'
    | '/'
    | '/events'
    | '/events_/$eventId/admin'
    | '/events_/$eventId/artist'
    | '/events_/$eventId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EventsRoute: typeof EventsRoute
  EventsEventIdAdminRoute: typeof EventsEventIdAdminRoute
  EventsEventIdArtistRoute: typeof EventsEventIdArtistRoute
  EventsEventIdIndexRoute: typeof EventsEventIdIndexRoute
}

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events_/$eventId/': {
      id: '/events_/$eventId/'
      path: '/events/$eventId'
      fullPath: '/events/$eventId'
      preLoaderRoute: typeof EventsEventIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events_/$eventId/artist': {
      id: '/events_/$eventId/artist'
      path: '/events/$eventId/artist'
      fullPath: '/events/$eventId/artist'
      preLoaderRoute: typeof EventsEventIdArtistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events_/$eventId/admin': {
      id: '/events_/$eventId/admin'
      path: '/events/$eventId/admin'
      fullPath: '/events/$eventId/admin'
      preLoaderRoute: typeof EventsEventIdAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EventsRoute: EventsRoute,
  EventsEventIdAdminRoute: EventsEventIdAdminRoute,
  EventsEventIdArtistRoute: EventsEventIdArtistRoute,
  EventsEventIdIndexRoute: EventsEventIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
